server:
  port: 8012

redis:
  host: localhost
  port: 6543
  username: autz
  password: autz

jwt:
  accessTokenExpirationInMinutes: 10
  refreshTokenExpirationInMinutes: 20

spring:
  datasource:
    password: autz
    url: "jdbc:postgresql://localhost:5480/autz-db"
    username: autz
    driver-class-name: org.postgresql.Driver