server:
  port: 8012

redis:
  host: autz-redis
  port: 6543
  username: autz
  password: autz

jwt:
  accessTokenExpirationInMinutes: 10
  refreshTokenExpirationInMinutes: 20
  secretKey: secretKey

spring:
  datasource:
    password: autz
    url: "jdbc:postgresql://autz-db:5432/autz-db"
    username: autz
    driver-class-name: org.postgresql.Driver