server:
  port: 8012

redis:
  host: localhost
  port: 6379
  username: autz
  password: autz

jwt:
  accessTokenExpirationInMinutes: 10
  refreshTokenExpirationInMinutes: 20
  secretKey: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey

eureka:
  enable:
    discovery: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    password: autz
    url: "jdbc:postgresql://localhost:5480/autz-db"
    username: autz
    driver-class-name: org.postgresql.Driver