server:
  port: 8081

security:
  enabled: true

eureka:
  enable:
    discovery: false

spring:
  datasource:
    password: editor
    url: "jdbc:postgresql://editor-db:5432/editor-db"
    username: editor
    driver-class-name: org.postgresql.Driver