server:
  port: 8081

security:
  enabled: true

auth:
  version: "v2"

eureka:
  enable:
    discovery: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  datasource:
    password: editor
    url: "jdbc:postgresql://localhost:5481/editor-db"
    username: editor
    driver-class-name: org.postgresql.Driver