server:
  port: 8082

security:
  enabled: true

eureka:
  client:
    enabled: false
  enable:
    discovery: false

spring:
  datasource:
    password: signer
    url: "jdbc:postgresql://signer-db:5432/signer-db"
    username: signer
    driver-class-name: org.postgresql.Driver
