server:
  port: 8082

security:
  enabled: true

auth:
  version: "v2"

spring:
  datasource:
    password: signer
    url: "jdbc:postgresql://localhost:5482/signer-db"
    username: signer
    driver-class-name: org.postgresql.Driver
