server:
  port: 8082

security:
  enabled: true

auth:
  version: "v2"

eureka:
  instance:
    hostname: localhost
  enable:
    discovery: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  datasource:
    password: signer
    url: "jdbc:postgresql://localhost:5482/signer-db"
    username: signer
    driver-class-name: org.postgresql.Driver
